development:
  adapter: postgresql
  encoding: unicode
  database: dev
  pool: 5
  username: mckale
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: ebdb
  host: aa2xr3j1fcg543.cezixpwe6tjj.us-west-2.rds.amazonaws.com
  port: 5432
  username: mckale
  password: TestPassword
